### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by krzychu124** [kianzarrin/UnitedUI#1]
I've got few questions and thoughts about this thingy 😃 

Why your proposed approach is so strict?
I mean if it suppose to be buttons container for various mods it is designed in a way that I don't think many of devs would see anything useful with it. It's too much work for you and them to get any benefit

After quick look into the code I think that the main problem is that you misunderstood buttons container responsibility or I don't understand purpose of it 🙃 

In my opinion, main and probably the only job for this container should be registering buttons and displaying them in order(or not) basically doing layout (could be configurable (say 2/3/4 columns * X rows - depends on number of buttons, might be configurable in options or container settings ui)). You can even make it resizable, but I don't think you should care which mod is going to use it.

You could provide a simple way to register button/toggle and then call defined action when clicked. 
That's all. It should be as simple as that. 
Then you could add new features like triggering via keybind, but it could be also as generic as possible.
Just make it data driven.

Create API for (un)registering buttons and pass click action through api interface to registered listener (mod)
eg. UnitedUIManager.
```ts
instantiateOrUpgrade: () => UnitedManager;// you can skip it if you don't plan to add breaking changes
register: (properties) => bool;
unregister: (name or something) => void; 
```

Example properties available through API(pseudocode):
```ts
icon: texture2d/state or atlas //(fallback to your template if null); you can split to multiple properties(one per state)
tooltipText: string;
clickAction: () => void;
tool: () => ToolBase instance;
```

At later stage you could make that manager versioned and upgradable. Say three mods use this lib with different versions. Each time manager initializes for each mod it would check if exist and if older version is already instantiated, it will upgrade it to the newer.
Always only single instance would be available.

_Pros (library api):_
- users forget(don't like) subscribing dependencies, game also forgets what was enabled so it's easy to end up on not working solution.
- also devs wouldn't have contact you if they want to change something, like texture, name, tooltip or something else you are going support.

I'm open on discussion 🙂

**Comment by kianzarrin** [comment]
Thanks @krzychu124 
UnitedUI is at the infant stage. My objective is to maximize value/time and there is a saying that you can achieve 80% of the work in 20% of the time. That is why I am doing a lot of task switching between my mods.

- The first objective of this mod is to get rid of the buttons under the road options panel (under the snapping button) which are often covered up by each other if not by the Road button if user uses an advanced toolbar.
- I will then patch other mods to fix their UI problems (or commit code to the github if possible). For example some mods have poor shortcuts like ModTools where Contol+S brings up the script but Control+Alt+S also does the same thing. Also, I hear Elektrix road tools and K button go of screen sometimes so I can fix that too.
- Also I don't like the fact that when I select road tools, a ton of panels opens up covering my screen like a parallel road tool. I like to make them hidable when I am drawing roads even if they are active. for example I will try to make the panel for Parallel road tool hidable even when it is active so that it does not cover up too much of the screen. 
- Then I would like to provide an interface for other mods to add buttons.
- I also like to make the buttons groupable. user can select groups to be organized in rows and columns OR he can choose all in the same raw/column separated by a separator line).

**Comment by kianzarrin** [comment]
@krzychu124 are your concerns addressed? should I close this issue?

**Comment by krzychu124** [comment]
Closing 😉
